apiVersion: v1
kind: Service
metadata:
  name: firebase-app
  labels:
    app: firebase-app
spec:
  selector:
    app: firebase-app
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
